//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAktivnosti
    {
        public int id { get; set; }
        public int idProjekta { get; set; }
        public int idNadredjenog { get; set; }
        public int idRadnika { get; set; }
        public string Naslov { get; set; }
        public string opis { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> end { get; set; }
        public Nullable<System.DateTime> startRadnik { get; set; }
    
        public virtual tblNadredjeni tblNadredjeni { get; set; }
        public virtual tblProjekti tblProjekti { get; set; }
        public virtual tblZaposleni tblZaposleni { get; set; }
    }
}
