//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjekti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProjekti()
        {
            this.tblAktivnostis = new HashSet<tblAktivnosti>();
        }
    
        public int id { get; set; }
        public int idNadredjenog { get; set; }
        public string nazivProjekta { get; set; }
        public string Opis { get; set; }
        public Nullable<bool> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAktivnosti> tblAktivnostis { get; set; }
        public virtual tblNadredjeni tblNadredjeni { get; set; }
    }
}
